/**
 * Antigravity OS v2.1 - CLI Executor
 * Wraps `gh copilot suggest` for automatic code generation.
 * Cleans CLI output junk and returns usable code.
 */

import { execFile } from "node:child_process";
import { promisify } from "node:util";
import fs from "node:fs/promises";
import { Logger } from "@antigravity-os/shared";

const execFileAsync = promisify(execFile);
const log = new Logger("cli-executor");

export interface CliExecutionResult {
  code: string;
  raw_output: string;
  lines_generated: number;
  execution_time_ms: number;
  source: "cli" | "fallback";
}

export class CliExecutor {
  private readonly timeout: number;
  private readonly maxBuffer: number;

  constructor(options?: { timeout?: number; maxBuffer?: number }) {
    this.timeout = options?.timeout ?? 60000;
    this.maxBuffer = options?.maxBuffer ?? 10 * 1024 * 1024;
  }

  /**
   * Execute `gh copilot suggest` with the given prompt content.
   * Falls back to saving the prompt as-is if the CLI is unavailable.
   */
  async execute(promptContent: string): Promise<CliExecutionResult> {
    const start = performance.now();

    try {
      // Write prompt to temp file to avoid shell escaping issues
      const tmpPath = `/tmp/antigravity_prompt_${Date.now()}.txt`;
      await fs.writeFile(tmpPath, promptContent, "utf-8");

      log.info("Executing gh copilot suggest", {
        prompt_length: promptContent.length,
      });

      const { stdout, stderr } = await execFileAsync(
        "gh",
        ["copilot", "suggest", "-t", "code", promptContent.slice(0, 1000)],
        {
          maxBuffer: this.maxBuffer,
          timeout: this.timeout,
          env: { ...process.env, GH_PROMPT: "disable" },
        }
      );

      // Clean up temp file
      await fs.unlink(tmpPath).catch(() => { });

      if (stderr && stderr.toLowerCase().includes("error")) {
        log.warn("Copilot CLI stderr", { stderr: stderr.slice(0, 500) });
      }

      const cleanedCode = this.stripCliJunk(stdout);
      const elapsed = performance.now() - start;

      log.info("Copilot CLI execution complete", {
        lines: cleanedCode.split("\n").length,
        duration_ms: Math.round(elapsed),
      });

      return {
        code: cleanedCode,
        raw_output: stdout,
        lines_generated: cleanedCode.split("\n").length,
        execution_time_ms: Math.round(elapsed),
        source: "cli",
      };
    } catch (error: any) {
      const elapsed = performance.now() - start;

      log.warn("Copilot CLI unavailable, using fallback", {
        error: error.message,
        duration_ms: Math.round(elapsed),
      });

      // Fallback: return prompt as commented code for manual processing
      const fallbackCode = [
        `// Generated by Antigravity OS Copilot v2.1 (fallback mode)`,
        `// gh copilot suggest was unavailable: ${error.message}`,
        `// Timestamp: ${new Date().toISOString()}`,
        `//`,
        `// TODO: Process the prompt below and replace this file with generated code.`,
        `//`,
        `// --- PROMPT START ---`,
        ...promptContent.split("\n").map((l) => `// ${l}`),
        `// --- PROMPT END ---`,
        "",
      ].join("\n");

      return {
        code: fallbackCode,
        raw_output: "",
        lines_generated: fallbackCode.split("\n").length,
        execution_time_ms: Math.round(elapsed),
        source: "fallback",
      };
    }
  }

  /**
   * Remove CLI boilerplate, ANSI codes, spinners, and markdown fences
   * from Copilot output.
   */
  stripCliJunk(output: string): string {
    let cleaned = output;

    const junkPatterns: RegExp[] = [
      // ANSI escape codes
      /\x1b\[[0-9;]*[a-zA-Z]/g,
      // Spinner characters
      /[⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⣾⣽⣻⢿⡿⣟⣯⣷◐◓◑◒⊙◉○●]/g,
      // Progress bars
      /\[([#=\->.\s]){3,}\]\s*\d*%?/g,
      // "Analyzing..." / "Thinking..." lines
      /^(Analyzing|Thinking|Scanning|Processing|Loading|Searching|Generating|Compiling).*\.{2,}\s*$/gm,
      // GitHub Copilot prefixes
      /^GitHub Copilot:\s*/gm,
      /^Here is your code:\s*/gm,
      /^Here's the .*:\s*/gm,
      // Generated-by comments
      /^\/\/\s*Generated by .*$/gm,
      /^#\s*Generated by .*$/gm,
      // Markdown code fences (opening/closing)
      /^```[a-z]*\n/g,
      /\n```\s*$/g,
    ];

    for (const pattern of junkPatterns) {
      cleaned = cleaned.replace(pattern, "");
    }

    // Collapse multiple blank lines
    cleaned = cleaned.replace(/\n{3,}/g, "\n\n");

    return cleaned.trim();
  }
}
