/**
 * Security and quality validation patterns for Copilot output.
 * Also includes CLI output cleaning.
 */

export interface ValidationIssue {
  type: "security" | "quality";
  severity: "error" | "warning";
  message: string;
  line?: number;
  pattern: string;
}

export const SECURITY_PATTERNS = [
  { pattern: /password\s*=\s*["'][^"']+["']/i, message: "Hardcoded password detected" },
  { pattern: /api_key\s*=\s*["'][^"']+["']/i, message: "Hardcoded API key detected" },
  { pattern: /secret\s*=\s*["'][^"']+["']/i, message: "Hardcoded secret detected" },
  { pattern: /token\s*=\s*["'][^"']+["']/i, message: "Hardcoded token detected" },
  { pattern: /AUTH.*=\s*False/i, message: "Authentication disabled" },
  { pattern: /eval\s*\(/, message: "Dangerous eval() usage" },
  { pattern: /exec\s*\(/, message: "Dangerous exec() usage" },
  { pattern: /except:\s*$/m, message: "Bare except clause (catches all exceptions)" },
  { pattern: /subprocess\.call\s*\(.*shell\s*=\s*True/i, message: "Shell injection risk: shell=True" },
  { pattern: /SELECT\s+.*\+\s*['"]/i, message: "Potential SQL injection (string concatenation)" },
  { pattern: /innerHTML\s*=/, message: "Potential XSS via innerHTML" },
  { pattern: /dangerouslySetInnerHTML/, message: "React XSS risk: dangerouslySetInnerHTML" },
];

export const QUALITY_PATTERNS = [
  { pattern: /def \w+\([^)]*\)\s*:(?!.*->)/, message: "Missing return type hint", severity: "warning" as const },
  { pattern: /def \w+[^]*?(?=\ndef |\n[^\s]|$)/, antiPattern: /"""/, message: "Missing docstring", severity: "warning" as const },
  { pattern: /\bprint\s*\(/, message: "Debug print statement (use logging)", severity: "warning" as const },
  { pattern: /TODO|FIXME|HACK|XXX/, message: "Unresolved TODO/FIXME marker", severity: "warning" as const },
  { pattern: /# type:\s*ignore/, message: "Type checking suppressed", severity: "warning" as const },
];

/**
 * Strip CLI junk from Copilot output to save tokens.
 */
export function stripCliJunk(output: string): string {
  const junkPatterns = [
    /^Thinking\.\.\.\s*/gm,
    /^Scanning files\.\.\.\s*/gm,
    /^GitHub Copilot:\s*/gm,
    /^Here is your code:\s*/gm,
    /^```[a-z]*\n/g,
    /\n```\s*$/g,
    /^\/\/ Generated by GitHub Copilot\s*/gm,
    /^# Generated by GitHub Copilot\s*/gm,
    /^\s*\n/gm, // Collapse multiple blank lines
  ];

  let cleaned = output;
  for (const pattern of junkPatterns) {
    cleaned = cleaned.replace(pattern, "");
  }

  return cleaned.trim();
}

/**
 * Run security and quality validation on file content.
 */
export function validateCode(content: string): ValidationIssue[] {
  const issues: ValidationIssue[] = [];
  const lines = content.split("\n");

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    for (const sec of SECURITY_PATTERNS) {
      if (sec.pattern.test(line)) {
        issues.push({
          type: "security",
          severity: "error",
          message: sec.message,
          line: i + 1,
          pattern: sec.pattern.source,
        });
      }
    }

    for (const qual of QUALITY_PATTERNS) {
      if (qual.pattern.test(line)) {
        if ("antiPattern" in qual && qual.antiPattern) {
          // Check if anti-pattern exists within a reasonable range
          const context = lines.slice(i, Math.min(i + 5, lines.length)).join("\n");
          if (qual.antiPattern.test(context)) continue;
        }
        issues.push({
          type: "quality",
          severity: qual.severity,
          message: qual.message,
          line: i + 1,
          pattern: qual.pattern.source,
        });
      }
    }
  }

  return issues;
}
