import fs from "node:fs/promises";
import path from "node:path";
import { Logger, respond, respondError } from "@antigravity-os/shared";
import type { CopilotContext } from "./types.js";
import type { ExecuteArgs, BatchExecuteArgs, ExecuteAndValidateArgs } from "../schemas.js";

const PROJECT_ROOT = process.env.PROJECT_ROOT || process.cwd();
const log = new Logger("copilot-server");

export async function handleExecute(ctx: CopilotContext, args: ExecuteArgs) {
  const { prompt_file: promptFile, output_file: outputFile } = args;
  const taskId = args.task_id ?? `task_${Date.now()}`;
  const useCache = args.use_cache ?? true;

  // Loop detection
  ctx.loopDetector.checkLoop(taskId);

  // Read prompt
  const promptPath = path.isAbsolute(promptFile) ? promptFile : path.join(ctx.memoryPath, promptFile);
  let promptContent: string;
  try {
    promptContent = await fs.readFile(promptPath, "utf-8");
  } catch {
    return respondError(`Prompt file not found: ${promptFile}`);
  }

  // Check cache
  if (useCache) {
    const cacheKey = ctx.cache.generateKey(promptContent, "");
    const cached = ctx.cache.get(cacheKey);
    if (cached) {
      const outPath = path.isAbsolute(outputFile) ? outputFile : path.join(PROJECT_ROOT, outputFile);
      await fs.mkdir(path.dirname(outPath), { recursive: true });
      await fs.writeFile(outPath, cached.response, "utf-8");

      return respond({
        status: "success",
        operation: "copilot_execute",
        summary: `Wrote cached result to ${outputFile}`,
        metadata: { output_file: outputFile, source: "cache", cache_key: cacheKey, hit_count: cached.hit_count },
      });
    }
  }

  // Save the prompt as output for the user/AI to process
  const outPath = path.isAbsolute(outputFile) ? outputFile : path.join(PROJECT_ROOT, outputFile);
  await fs.mkdir(path.dirname(outPath), { recursive: true });

  const outputContent = [
    `// Generated by Antigravity OS Copilot v2.0`,
    `// Prompt: ${promptFile}`,
    `// Task: ${taskId}`,
    `// Timestamp: ${new Date().toISOString()}`,
    `//`,
    `// TODO: Process the prompt below and replace this file with generated code.`,
    `//`,
    `// --- PROMPT START ---`,
    ...promptContent.split("\n").map((l) => `// ${l}`),
    `// --- PROMPT END ---`,
    "",
  ].join("\n");

  await fs.writeFile(outPath, outputContent, "utf-8");

  // Cache the result
  if (useCache) {
    const cacheKey = ctx.cache.generateKey(promptContent, "");
    ctx.cache.set(cacheKey, outputContent, { task_id: taskId, prompt_file: promptFile });
  }

  ctx.loopDetector.reset(taskId);

  return respond({
    status: "success",
    operation: "copilot_execute",
    summary: `Prompt saved to ${outputFile} for processing`,
    metadata: {
      output_file: outputFile,
      prompt_file: promptFile,
      task_id: taskId,
      source: "generated",
      output_length: outputContent.length,
    },
  });
}

export async function handleBatchExecute(ctx: CopilotContext, args: BatchExecuteArgs) {
  const { prompts } = args;

  if (!prompts || prompts.length === 0) {
    return respondError("No prompts provided");
  }

  // Conflict detection: check for duplicate output files
  const outputFiles = prompts.map((p) => p.output_file);
  const duplicates = outputFiles.filter((f, i) => outputFiles.indexOf(f) !== i);
  if (duplicates.length > 0) {
    return respondError(`Conflict: duplicate output files detected: ${[...new Set(duplicates)].join(", ")}`);
  }

  const results: Array<{ prompt_file: string; output_file: string; status: string; error?: string }> = [];

  for (const prompt of prompts) {
    try {
      await handleExecute(ctx, {
        prompt_file: prompt.prompt_file,
        output_file: prompt.output_file,
        task_id: prompt.task_id || `batch_${Date.now()}_${results.length}`,
        use_cache: true,
      });
      results.push({ prompt_file: prompt.prompt_file, output_file: prompt.output_file, status: "success" });
    } catch (err: any) {
      results.push({ prompt_file: prompt.prompt_file, output_file: prompt.output_file, status: "error", error: err.message });
    }
  }

  const succeeded = results.filter((r) => r.status === "success").length;

  return respond({
    status: "success",
    operation: "copilot_batch_execute",
    summary: `Batch: ${succeeded}/${prompts.length} succeeded`,
    metadata: { total: prompts.length, succeeded, failed: prompts.length - succeeded, results },
  });
}

export async function handleExecuteAndValidate(ctx: CopilotContext, args: ExecuteAndValidateArgs) {
  const { prompt_file: promptFile, output_file: outputFile } = args;
  const requirements = args.requirements ?? [];
  const autoApprove = args.auto_approve_if_valid ?? false;
  const maxRetries = args.max_retries ?? 3;

  const taskId = `${promptFile}:${outputFile}`;

  // Loop detection
  ctx.loopDetector.checkLoop(taskId);

  // Read prompt
  const promptPath = path.isAbsolute(promptFile) ? promptFile : path.join(ctx.memoryPath, promptFile);
  let promptContent: string;
  try {
    promptContent = await fs.readFile(promptPath, "utf-8");
  } catch {
    return respondError(`Prompt file not found: ${promptFile}`);
  }

  // Check cache
  const cacheKey = ctx.cache.generateKey(promptContent, outputFile);
  const cached = ctx.cache.get(cacheKey);
  if (cached) {
    const outPath = path.isAbsolute(outputFile) ? outputFile : path.join(PROJECT_ROOT, outputFile);
    await fs.mkdir(path.dirname(outPath), { recursive: true });
    await fs.writeFile(outPath, cached.response, "utf-8");

    // Validate cached code
    const validation = ctx.validator.validate(cached.response, requirements);

    return respond({
      status: "cached",
      operation: "copilot_execute_and_validate",
      summary: `Wrote cached result to ${outputFile}`,
      metadata: {
        output_file: outputFile,
        source: "cache",
        cache_key: cacheKey,
        hit_count: cached.hit_count,
        validation: {
          passed: validation.valid,
          issues: validation.issues,
          security_score: validation.security_score,
          quality_score: validation.quality_score,
          recommendation: validation.valid ? "APPROVE" : "REVIEW_REQUIRED",
        },
      },
    });
  }

  // Execute Copilot CLI
  log.info("Running copilot_execute_and_validate", { prompt_file: promptFile, output_file: outputFile });

  let result = await ctx.cliExecutor.execute(promptContent);
  let validation = ctx.validator.validate(result.code, requirements);
  const healAttempts: Array<{ attempt: number; issues: unknown[] }> = [];

  // Auto-heal loop: retry with correction prompt on validation failure
  let attempt = 0;
  while (!validation.valid && attempt < maxRetries && result.source === "cli") {
    attempt++;
    log.info("Auto-heal: retrying after validation failure", {
      attempt,
      max_retries: maxRetries,
      issue_count: validation.issues.length,
    });

    healAttempts.push({ attempt, issues: validation.issues });

    const issuesSummary = validation.issues
      .map((i) => `- [${i.severity}] Line ${i.line ?? "?"}: ${i.message}`)
      .join("\n");

    const correctionPrompt = [
      "The following code has validation issues that must be fixed:",
      "",
      "=== ORIGINAL CODE ===",
      result.code,
      "=== END CODE ===",
      "",
      "=== VALIDATION ISSUES ===",
      issuesSummary,
      "=== END ISSUES ===",
      "",
      "Rewrite the code to fix ALL listed issues. Output only the corrected code.",
    ].join("\n");

    result = await ctx.cliExecutor.execute(correctionPrompt);
    validation = ctx.validator.validate(result.code, requirements);
  }

  // Write output
  const outPath = path.isAbsolute(outputFile) ? outputFile : path.join(PROJECT_ROOT, outputFile);
  await fs.mkdir(path.dirname(outPath), { recursive: true });
  await fs.writeFile(outPath, result.code, "utf-8");

  // Cache if valid
  if (validation.valid) {
    ctx.cache.set(cacheKey, result.code, {
      task_id: taskId,
      prompt_file: promptFile,
      source: result.source,
    });
    ctx.loopDetector.reset(taskId);
  }

  return respond({
    status: validation.valid ? "success" : "validation_failed",
    operation: "copilot_execute_and_validate",
    summary: validation.valid
      ? `Generated and validated ${outputFile} (${result.lines_generated} lines)${healAttempts.length > 0 ? ` after ${healAttempts.length} auto-heal attempt(s)` : ""}`
      : `Generated ${outputFile} but validation FAILED after ${healAttempts.length} auto-heal attempt(s)`,
    metadata: {
      output_file: outputFile,
      prompt_file: promptFile,
      source: result.source,
      lines_generated: result.lines_generated,
      execution_time_ms: result.execution_time_ms,
      auto_heal: {
        enabled: maxRetries > 0,
        attempts: healAttempts.length,
        max_retries: maxRetries,
        history: healAttempts,
      },
      validation: {
        passed: validation.valid,
        issues: validation.issues,
        security_score: validation.security_score,
        quality_score: validation.quality_score,
        recommendation: validation.valid ? "APPROVE" : "REVIEW_REQUIRED",
      },
      preview: result.code.slice(0, 300) + (result.code.length > 300 ? "..." : ""),
      auto_approved: autoApprove && validation.valid,
    },
  });
}
